### ISSUE TITLE
PySimpleGUI

### ISSUE THREAD

**Issue by Lindanvdw** [abrignoni/DLEAPP#4]
Still with PySimpleGUI which is payversion now, is it possible to use the same as in iLeapp / aLeapp?

**Comment by abrignoni** [comment]
The LEAPPs don't use PySimpleGUI anymore. It is pure tkinter now.

**Comment by Lindanvdw** [comment]
oh but it's in the requirements file of dLeapp and wLeapp? PySimpleGUI==4.16.0

**Comment by abrignoni** [comment]
Dleapp has no artifacts. Long story short the folks that said they would
volunteer to create some never did.

DLEAPP will be deprecated soon since it supports zero devices.

All the other LEAPPs are active and updated as stated.

**Comment by Lindanvdw** [comment]
ah I see! Thanks!
